### ISSUE TITLE
build fails with `undefined reference to `major'`

### ISSUE THREAD

**Issue by morganrallen** [Ebiroll/qemu_esp32#12]
This is the output using the instructions from the readme

```
/usr/bin/ld: qga/commands-posix.o: in function `dev_major_minor':
/home/morgan/devel/qemu-xtensa-esp32/qga/commands-posix.c:656: undefined reference to `major'
/usr/bin/ld: /home/morgan/devel/qemu-xtensa-esp32/qga/commands-posix.c:657: undefined reference to `minor'
collect2: error: ld returned 1 exit status
```

There are several warning prior
```
/home/morgan/devel/qemu-xtensa-esp32/qga/commands-posix.c: In function ‘dev_major_minor’:
/home/morgan/devel/qemu-xtensa-esp32/qga/commands-posix.c:656:21: warning: implicit declaration of function ‘major’ [-Wimplicit-function-declaration]
         *devmajor = major(st.st_rdev);
                     ^~~~~
/home/morgan/devel/qemu-xtensa-esp32/qga/commands-posix.c:656:21: warning: nested extern declaration of ‘major’ [-Wnested-externs]
/home/morgan/devel/qemu-xtensa-esp32/qga/commands-posix.c:657:21: warning: implicit declaration of function ‘minor’; did you mean ‘mincore’? [-Wimplicit-function-declaration]
         *devminor = minor(st.st_rdev);
                     ^~~~~
                     mincore
/home/morgan/devel/qemu-xtensa-esp32/qga/commands-posix.c:657:21: warning: nested extern declaration of ‘minor’ [-Wnested-externs]

```

**Comment by Ebiroll** [comment]
What operating system and version are you using when compiling?

**Comment by morganrallen** [comment]
Ubuntu 19.04

Running with `qemu-system-xtensa -d guest_errors,unimp  -cpu esp32 -M esp32 -m 4M -s`

**Comment by Ebiroll** [comment]
You probably already solved this. 
Do a #include <sys/sysmacros.h>

**Comment by morganrallen** [comment]
I actually just removed the references to `major`/`minor` :)))

**Comment by Jiangdiii** [comment]
I met this Problem,too. My OS is Unbuntu 20.04 LTS. 
After I add #include <sys/sysmacros.h>. I solved this issiue.

**Comment by TaoTaoNie** [comment]
> I met this Problem,too. My OS is Unbuntu 20.04 LTS.
> After I add #include <sys/sysmacros.h>. I solved this issiue.

which file to add #include <sys/sysmacros.h>?

**Comment by DanielWood** [comment]
> > I met this Problem,too. My OS is Unbuntu 20.04 LTS.
> > After I add #include <sys/sysmacros.h>. I solved this issiue.
> 
> which file to add #include <sys/sysmacros.h>?

commands-posix.c
