### ISSUE TITLE
Error in esp_gdbstub_arch.h

### ISSUE THREAD

**Issue by cartu32** [Ebiroll/qemu_esp32#29]
Hi, I'm trying to follow the Quick Start steps, but when I do step 3, it shows me an error that the esp_gdbstub_arch.h file cannot be found. This error appears after executing the "make" command, after having executed "make menuconfig". I show below the error I get through the screen

CC build/esp_serial_slave_link/essl_spi.o
CC build/esp_serial_slave_link/essl_sdio.o
CC build/esp_serial_slave_link/essl.o
AR build/esp_serial_slave_link/libesp_serial_slave_link.a
CC build/esp_system/panic.o
In file included from /root/esp-idf/components/esp_system/panic.c:58:
/root/esp-idf/components/esp_gdbstub/include/esp_gdbstub.h:17:10: fatal error: esp_gdbstub_arch.h: No such file or directory
 #include "esp_gdbstub_arch.h"
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
/root/esp-idf/make/component_wrapper.mk:291: recipe for target 'panic.o' failed
make[1]: *** [panic.o] Error 1
/root/esp-idf//make/project.mk:642: recipe for target 'component-esp_system-build' failed
make: *** [component-esp_system-build] Error 2

Could I be doing some Quick Start step incorrectly?

From already thank you very much

**Comment by Ebiroll** [comment]
Sorry, I should update that step. It might not work with newer version of esp-idf-
Please read here.
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/build-system.html
