### ISSUE TITLE
error: variable has incomplete type 'struct stat64'

### ISSUE THREAD

**Issue by fanzhiri** [Ebiroll/qemu_esp32#34]
CXX   xtensa-softmmu/hw/xtensa/MemoryMapped.o
/Users/fanzhiri/GitHub/qemu-xtensa-esp32/hw/xtensa/MemoryMapped.cpp:132:17: error: variable has incomplete type 'struct stat64'
  struct stat64 statInfo;
                ^
/Users/fanzhiri/GitHub/qemu-xtensa-esp32/hw/xtensa/MemoryMapped.cpp:132:10: note: forward declaration of 'stat64'
  struct stat64 statInfo;

**Comment by fanzhiri** [comment]
在qemu-xtensa-esp32/hw/xtensa/MemoryMapped.cpp 添加两行
#define stat64 stat
#define fstat64 fstat

**Comment by elesos** [comment]
666
