### ISSUE TITLE
[Ubuntu17.04] Compilation error

### ISSUE THREAD

**Issue by bonnefoi** [Ebiroll/qemu_esp32#4]
Hello,

I've the following error on Ubuntu 17.04 
hw/xtensa/xtfpga.o: In function `lx_init':
/home/pef/qemu-xtensa-esp32/hw/xtensa/xtfpga.c:323: undefined reference to `load_device_tree'
collect2: error: ld returned 1 exit status
Makefile:197: recipe for target 'qemu-system-xtensa' failed
make[1]: *** [qemu-system-xtensa] Error 1
Makefile:204: recipe for target 'subdir-xtensa-softmmu' failed
make: *** [subdir-xtensa-softmmu] Error 2

I've googled it but no answers.

Any ideas ?

**Comment by Ebiroll** [comment]
Oh. If you use the patch for the 2.9 version i would say,
git submodule update --init dtc
However load_device_tree is not used so I removed the call.
Try 
>git pull
and recompile.
